use super::kinds::{
    adx, alma, atr, bollinger, cci, chandelier, ema, hma, ichimoku, keltner, macd, mfi, obv,
    parabolic_sar, pivot_points, ppo, roc, rsi, sma, stochastic, supertrend, volume, vwap,
    williams_r, wma,
};
use super::params::ParamSchema;
use super::trait_def::Indicator;

pub struct IndicatorDef {
    pub id: &'static str,
    pub name: &'static str,
    /// Compact label used on the shortcut toolbar (e.g. "EMA", "VOL").
    pub short_name: &'static str,
    pub params: ParamSchema,
    pub likes: u32,
    pub description: &'static str,
    pub factory: fn() -> Box<dyn Indicator>,
}

static DEFS: &[IndicatorDef] = &[
    IndicatorDef {
        id: ema::ID,
        name: ema::NAME,
        short_name: "EMA",
        params: ema::SCHEMA,
        likes: ema::LIKES,
        description: "Exponential Moving Average. Weights recent prices more heavily than older ones, making it more responsive to new information than a simple moving average.",
        factory: ema::factory,
    },
    IndicatorDef {
        id: sma::ID,
        name: sma::NAME,
        short_name: "SMA",
        params: sma::SCHEMA,
        likes: sma::LIKES,
        description: "Simple Moving Average. Equal-weight average of the last N closing prices. Smoother than EMA but slower to react.",
        factory: sma::factory,
    },
    IndicatorDef {
        id: wma::ID,
        name: wma::NAME,
        short_name: "WMA",
        params: wma::SCHEMA,
        likes: wma::LIKES,
        description: "Weighted Moving Average. Linearly weights recent prices more heavily, falling between SMA and EMA in responsiveness.",
        factory: wma::factory,
    },
    IndicatorDef {
        id: hma::ID,
        name: hma::NAME,
        short_name: "HMA",
        params: hma::SCHEMA,
        likes: hma::LIKES,
        description: "Hull Moving Average. Uses weighted moving averages to reduce lag while maintaining smoothness.",
        factory: hma::factory,
    },
    IndicatorDef {
        id: alma::ID,
        name: alma::NAME,
        short_name: "ALMA",
        params: alma::SCHEMA,
        likes: alma::LIKES,
        description: "Arnaud Legoux Moving Average. Uses a Gaussian distribution of weights to minimize noise and lag.",
        factory: alma::factory,
    },
    IndicatorDef {
        id: bollinger::ID,
        name: bollinger::NAME,
        short_name: "BB",
        params: bollinger::SCHEMA,
        likes: bollinger::LIKES,
        description: "Bollinger Bands. Standard deviation bands around an SMA. Bands widen during volatile periods and narrow during calm ones.",
        factory: bollinger::factory,
    },
    IndicatorDef {
        id: keltner::ID,
        name: keltner::NAME,
        short_name: "KC",
        params: keltner::SCHEMA,
        likes: keltner::LIKES,
        description: "Keltner Channel. ATR-based volatility bands around an EMA. Tighter than Bollinger during low volatility, wider during high.",
        factory: keltner::factory,
    },
    IndicatorDef {
        id: rsi::ID,
        name: rsi::NAME,
        short_name: "RSI",
        params: rsi::SCHEMA,
        likes: rsi::LIKES,
        description: "Relative Strength Index. Oscillates between 0 and 100. Readings above 70 often indicate overbought conditions; below 30, oversold.",
        factory: rsi::factory,
    },
    IndicatorDef {
        id: volume::ID,
        name: volume::NAME,
        short_name: "VOL",
        params: volume::SCHEMA,
        likes: volume::LIKES,
        description: "Trading volume per bar with a simple moving average overlay (VMA). Up bars use the up color, down bars the down color.",
        factory: volume::factory,
    },
    IndicatorDef {
        id: macd::ID,
        name: macd::NAME,
        short_name: "MACD",
        params: macd::SCHEMA,
        likes: macd::LIKES,
        description: "MACD. Trend-following momentum indicator showing the relationship between two EMAs. Histogram shows divergence from signal.",
        factory: macd::factory,
    },
    IndicatorDef {
        id: ppo::ID,
        name: ppo::NAME,
        short_name: "PPO",
        params: ppo::SCHEMA,
        likes: ppo::LIKES,
        description: "Percentage Price Oscillator. Like MACD but expressed as a percentage, making it comparable across different price levels.",
        factory: ppo::factory,
    },
    IndicatorDef {
        id: stochastic::ID,
        name: stochastic::NAME,
        short_name: "STOCH",
        params: stochastic::SCHEMA,
        likes: stochastic::LIKES,
        description: "Slow Stochastic Oscillator. Compares closing price to the high-low range. %K above 80 suggests overbought; below 20, oversold.",
        factory: stochastic::factory,
    },
    IndicatorDef {
        id: cci::ID,
        name: cci::NAME,
        short_name: "CCI",
        params: cci::SCHEMA,
        likes: cci::LIKES,
        description: "Commodity Channel Index. Measures deviation from the statistical mean. Readings above +100 or below -100 suggest extreme conditions.",
        factory: cci::factory,
    },
    IndicatorDef {
        id: williams_r::ID,
        name: williams_r::NAME,
        short_name: "%R",
        params: williams_r::SCHEMA,
        likes: williams_r::LIKES,
        description: "Williams %R. Momentum oscillator ranging from -100 to 0. Above -20 suggests overbought; below -80, oversold.",
        factory: williams_r::factory,
    },
    IndicatorDef {
        id: roc::ID,
        name: roc::NAME,
        short_name: "ROC",
        params: roc::SCHEMA,
        likes: roc::LIKES,
        description: "Rate of Change. Percentage change between current price and N bars ago. Positive values indicate upward momentum.",
        factory: roc::factory,
    },
    IndicatorDef {
        id: mfi::ID,
        name: mfi::NAME,
        short_name: "MFI",
        params: mfi::SCHEMA,
        likes: mfi::LIKES,
        description: "Money Flow Index. Volume-weighted RSI. Above 80 suggests overbought with heavy volume; below 20, oversold.",
        factory: mfi::factory,
    },
    IndicatorDef {
        id: obv::ID,
        name: obv::NAME,
        short_name: "OBV",
        params: obv::SCHEMA,
        likes: obv::LIKES,
        description: "On Balance Volume. Cumulative volume flow — adds volume on up days, subtracts on down days. Rising OBV suggests accumulation.",
        factory: obv::factory,
    },
    IndicatorDef {
        id: vwap::ID,
        name: vwap::NAME,
        short_name: "VWAP",
        params: vwap::SCHEMA,
        likes: vwap::LIKES,
        description: "Volume Weighted Average Price. Average price weighted by volume, resetting each session. Key institutional reference level.",
        factory: vwap::factory,
    },
    IndicatorDef {
        id: atr::ID,
        name: atr::NAME,
        short_name: "ATR",
        params: atr::SCHEMA,
        likes: atr::LIKES,
        description: "Average True Range. Measures market volatility by decomposing the range of each bar. Higher ATR means more volatile.",
        factory: atr::factory,
    },
    IndicatorDef {
        id: adx::ID,
        name: adx::NAME,
        short_name: "ADX",
        params: adx::SCHEMA,
        likes: adx::LIKES,
        description: "Average Directional Index. Measures trend strength (not direction). ADX above 25 suggests a strong trend; +DI/-DI show direction.",
        factory: adx::factory,
    },
    IndicatorDef {
        id: supertrend::ID,
        name: supertrend::NAME,
        short_name: "ST",
        params: supertrend::SCHEMA,
        likes: supertrend::LIKES,
        description: "Supertrend. ATR-based trend-following overlay. Green when price is in uptrend, red in downtrend. Useful for trailing stop levels.",
        factory: supertrend::factory,
    },
    IndicatorDef {
        id: ichimoku::ID,
        name: ichimoku::NAME,
        short_name: "ICHI",
        params: ichimoku::SCHEMA,
        likes: ichimoku::LIKES,
        description: "Ichimoku Cloud. All-in-one trend indicator showing support, resistance, momentum, and trend direction via five plotted lines and a shaded cloud.",
        factory: ichimoku::factory,
    },
    IndicatorDef {
        id: chandelier::ID,
        name: chandelier::NAME,
        short_name: "CE",
        params: chandelier::SCHEMA,
        likes: chandelier::LIKES,
        description: "Chandelier Exit. ATR-based trailing stop levels. Long exit below price for longs, short exit above for shorts.",
        factory: chandelier::factory,
    },
    IndicatorDef {
        id: parabolic_sar::ID,
        name: parabolic_sar::NAME,
        short_name: "SAR",
        params: parabolic_sar::SCHEMA,
        likes: parabolic_sar::LIKES,
        description: "Parabolic SAR. Trailing stop-and-reverse dots. Dots below price indicate uptrend, above indicate downtrend.",
        factory: parabolic_sar::factory,
    },
    IndicatorDef {
        id: pivot_points::ID,
        name: pivot_points::NAME,
        short_name: "PP",
        params: pivot_points::SCHEMA,
        likes: pivot_points::LIKES,
        description: "Pivot Points. Support and resistance levels calculated from the previous session's HLC. Available in Standard, Fibonacci, and Woodie variants.",
        factory: pivot_points::factory,
    },
];

pub fn all() -> &'static [IndicatorDef] {
    DEFS
}

pub fn get(id: &str) -> Option<&'static IndicatorDef> {
    DEFS.iter().find(|d| d.id == id)
}
