[package]
name = "Zaned"
version = "0.1.0"
edition = "2024"

[dependencies]
zaned-core = { path = "../../crates/core" }
zaned-api-client = { path = "../../crates/api-client" }
zaned-chart-core = { path = "../../crates/chart-core" }
eframe = "0.34.1"
egui = "0.34.1"
egui-phosphor = "0.12"
tokio = { version = "1.50", features = ["rt-multi-thread"] }
wgpu = "29"
egui-wgpu = "0.34"
bytemuck = { version = "1", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
